[database]
dsn = "postgres://clocktower:clocktower@db:5432/clocktower?sslmode=disable"
migration = "postgres://clocktower:clocktower@0.0.0.0:5432/clocktower?sslmode=disable&x-migrations-table=migrations"

[debug]
url = "http://localhost:8000/"
