---
version: '3'

services:
  api:
    build:
      context: .
    volumes:
      - .:/go/src/github.com/gochrono/clocktower
    environment:
      CLOCKTOWER_DSN: postgres://clocktower:clocktower@db:5432/clocktower?sslmode=disable
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    restart: always
    image: postgres:11.3-alpine
    environment:
      POSTGRES_DB: "clocktower"
      POSTGRES_USER: "clocktower"
      POSTGRES_PASSWORD: "clocktower"
      # volumes:
      # - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
