---
version: '3'

services:
  api:
    build:
      context: .
    volumes:
      - .:/go/src/github.com/gochrono/castle
    environment:
      CASTLE_DSN: postgres://castle:castle@db:5432/castle?sslmode=disable
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    restart: always
    image: postgres:11.3-alpine
    environment:
      POSTGRES_DB: "castle"
      POSTGRES_USER: "castle"
      POSTGRES_PASSWORD: "castle"
      # volumes:
      # - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
